services:
  mariadb:
    image: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=${ROOT_PASSWORD_DB}
      - MARIADB_USER=${LOGIN_DB}
      - MARIADB_PASSWORD=${PASSWORD_DB}
      - MARIADB_DATABASE=${NAME_DB}
    ports:
      - 3307:3306
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
      - ./bd_data:/var/lib/mysql/mariadb
    container_name: c_mariadb
  monapache:
    image: jtrognon/monapache
    volumes:
      - ./:/var/www/html
    ports:
      - 8082:80
    container_name: c_monapache
  monubuntu:
    image: jtrognon/monubuntu
    container_name: c_monubuntu
  phpmyadmin:
    image: phpmyadmin
    environment:
      - PMA_HOST=mariadb
    ports:
      - 8083:80
    container_name: c_monphpmyadmin
